version: '3'

services:

  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskdb

  cdn:
    image: nginx:latest
    ports:
      - "8081:80"